name: "[Dispath] Docker push"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'enter version(x.y.z)'
        required: true
        default: '1.0.0'
      container_arch:
        type: choice
        description: 'choose container architecture'
        default: linux/amd64,linux/arm64
        options:
          - "linux/amd64"
          - "linux/arm64"
          - "linux/amd64,linux/arm64"

env:
  ARCH: ${{ github.event.inputs.container_arch }}
  VERSION: ${{ github.event.inputs.version }}

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: tagging
        run: |
          git config user.email admin@cloudforet.io
          git config user.name cloudforet-admin
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

  docker:
    runs-on: ubuntu-latest
    needs: tagging
    env:
      VERSION: ${{ needs.tagging.outputs.version }}
    steps:
      - name: Checkout
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: tjfals333/plugin-google-collector:${{ env.VERSION }}